# -*- coding: utf-8 -*-
"""cal1_1_v8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1unc1o_4UGigULPslF4OV-G7qy9mL7RQS
"""

# Murphy Campbell
# email: murphybcampbell@googlemail.com
# TTA Data Academy Home Learning: Seession 2, Calculator operation task
# Reference: https://www.w3schools.com/python/default.asp 


num1,num2,input1,input2 = 0,0,0,0
char =""
ops = {}



def cal(char,num1,num2):   # Declare calculator procedure with inputs
    char,x,y = char,num1,num2     # Assign passed in values to variables
    

    ops = {"a":x+y,                
           "b":x-y,               
           "c":x*y,
           "d":x**y,
           "e":x/y}
           

# Declare dictionary to hold keys and maths
# operation statements
 
    print("Result of calculation:\n",ops[char])   
    
    

 # Print result of maths operation from user input values                                                  
                                                  

print("Please enter two numbers to be operated upon\nPlease enter the first number" )
num1 = float(input(input1))
    
      
print("Please enter the second number\n")
num2 = float(input(input2))
                                    

 
print("======Calculator Menu ==============\n")
print('            "a": Add             ')
print('            "b": Sub             ')
print('            "c": times           ')
print('            "d": sqr             ')
print('            "e": div             ')
print('Please key in a letter "a" - "f" ')
char = str(input(char))
print("===================================\n")
              

                                

cal(char,num1,num2)
# Call calcualator with user provided inputs



try:
    number = eval(input("Input a number: "))
    print("The number you input is,".number)
except NameError as ex:
   print("Exception:", ex)



help(str)