# -*- coding: utf-8 -*-
"""Currency_convertor1_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17MjPSZkLqF62wifgSmIFTCPrrMDaQUnW
"""



# Murphy Campbell
# email: murphybcampbell@googlemail.com
# TTA Data Academy Home Learning: Seession 2, 
# Sterling Pound to US Dollar currency convertor

# Reference: https://www.python.org
# Reference: https://www.w3schools.com/python/default.asp 


# Map of variables #
# Sterling One Pound to US Dollar Conversion rate: Pound_rate_US
# Pound to US Dollar Conversion rate = 1.36 (01/11/2021)
# keyed in store for pounds to be converted to dollars: input_p
# Converted pounds to dollar: conv_pounds


Pound_rate_US = 1.36
input_p = 0.00
conv_pounds = 0.00


def conv_pd(input_p,conv_pounds):
    print("Sterling Pounds to US Dollar convertor\n")
    print("Please enter the amount of pounds you wish to convert\n")
    input_p = float(input())
    conv_pounds = input_p * Pound_rate_US
    
    return conv_pounds


conv_pounds = conv_pd(input_p,conv_pounds)
print("The conversion value is",conv_pounds, "Dollars")

num1,num2 = 0.00,0.00

def function1():
    return function2

def function2(num1,num2):
    num1,num2 = 0.00,0.00
    result = num1 + num2
    return result
    #print('Function 2')

function2(num1,num2)

num1,num2 = 2.00,7.00