# -*- coding: utf-8 -*-
"""Motor_Cycle1_v6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_0_lnjeY8TMyXAhCgdY0nVXgxOV4JtRA
"""



# Murphy Campbell
# email: murphybcampbell@googlemail.com
# TTA Data Academy Home Learning: Seession 2, 
# Motor Cycle depreciation task
# Reference: https://www.python.org
# Reference: https://www.w3schools.com/python/default.asp 



# Map of variables #
# Depreciation percentage: depr_pcnt
# Motor Cycle starting price: mtr_cycle_sp
# Motor Cycle depreciation value: mtr_cycle_dv

values = []



# Declare depreciation function with inputs
# Assign passed in values to variables


values = [None for _ in range(7)]

def depr(depr_pcnt,mtr_cycle_sp,mtr_cycle_dv): 
    i = 0
     
    mtr_cycle_dv = (mtr_cycle_sp - (mtr_cycle_sp * depr_pcnt))
    print("Motor Cycle depeciation values",mtr_cycle_dv)
    while i < 7:
      
     if mtr_cycle_dv > 1000.00: 
      values[i] = mtr_cycle_dv
      mtr_cycle_dv = (mtr_cycle_dv - (mtr_cycle_dv * depr_pcnt))
      values[i] = mtr_cycle_dv
     if mtr_cycle_dv < 1000.00:
      break

     
     i = i + 1
    return values
    

depr(depr_pcnt,mtr_cycle_sp,mtr_cycle_dv)
depr_pcnt,mtr_cycle_sp,mtr_cycle_dv = 0.10,2000.00,00.00

print("Motor Cycle depeciation values",values)